trigger: none

parameters:
  - name: platform
    displayName: 'Platform'
    type: string
    default: 'Aws'
    values:
      - Aws
      - Azure

  - name: clientName
    displayName: 'Client Name'
    type: string

  - name: accountName
    displayName: 'Cloud Account Name'
    type: string

  - name: environment
    displayName: 'Environment'
    type: string
    default: 'NPD'
    values:
      - NPD
      - PRD

pool:
  vmImage: ubuntu-latest

stages:
- stage: DecommissionAccount
  displayName: "Decommission Account"
  jobs:
  - job: DisplayAccountInfo
    displayName: "Display Account Decommissioning Info"
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            
            echo
            echo "================================================"
            echo -e "\033[1;31m[IMPORTANT]\033[0m Ensure you have backed up all necessary data before proceeding with decommissioning."
            echo "================================================"
            echo
            echo -e "\033[1m\033[4mDecommissioning Account Information:\033[0m"
            echo
            # Set the text color to red and make it bold
            RED_BOLD='\033[1m\033[31m'
            # Reset the text color and formatting to default
            NO_COLOR='\033[0m'
            YELLOW_BOLD='\033[1m\033[33m'

            echo -e "${YELLOW_BOLD}Decommissioning Account Information:${NO_COLOR}"
            echo -e "Platform: ${RED_BOLD}${{ parameters.platform }}${NO_COLOR}"
            echo -e "Client Name: ${RED_BOLD}${{ parameters.clientName }}${NO_COLOR}"
            echo -e "Cloud Account Name: ${RED_BOLD}${{ parameters.accountName }}${NO_COLOR}"
            echo -e "Environment: ${RED_BOLD}${{ parameters.environment }}${NO_COLOR}"
            echo
            echo "================================================"
            echo -e "\033[1;31m[CRITICAL WARNING]\033[0m This action is irreversible. Proceed with caution."
            echo "================================================"
            echo


  - job: WaitForValidation
    pool: server
    displayName: Wait for approval to create account
    timeoutInMinutes: 30
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 22 # task times out in 1 day
        inputs:
          notifyUsers: |
            zaki.spofy@gmail.com
            zack.fatouh@outlook.fr
          instructions: >
            Please validate the decommissioning of the account with the following details:\n
            - Platform: ${{ parameters.platform }}\n
            - Client Name: ${{ parameters.clientName }}\n
            - Cloud Account Name: ${{ parameters.accountName }}\n
            - Environment: ${{ parameters.environment }}\n
            This action is irreversible. Proceed with caution.