trigger: none

parameters:
  - name: platform
    displayName: 'Platform'
    type: string
    default: 'Aws'
    values:
      - Aws
      - Azure

  - name: clientName
    displayName: 'Client Name'
    type: string

  - name: accountName
    displayName: 'Cloud Account Name'
    type: string

  - name: environment
    displayName: 'Environment'
    type: string
    default: 'NPD'
    values:
      - NPD
      - PRD

pool:
  vmImage: ubuntu-latest

stages:
- stage: DecommissionAccount
  displayName: "Decommission Account"
  jobs:
  - job: DisplayAccountInfo
    displayName: "Display Account Decommissioning Info"
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Set the text color to red and make it bold
            RED_BOLD='\033[1m\033[31m'
            # Reset the text color and formatting to default
            NO_COLOR='\033[0m'

            echo -e "${RED_BOLD}Decommissioning Account Information:${NO_COLOR}"
            echo -e "${RED_BOLD}Platform: ${{ parameters.platform }}${NO_COLOR}"
            echo -e "${RED_BOLD}Client Name: ${{ parameters.clientName }}${NO_COLOR}"
            echo -e "${RED_BOLD}Cloud Account Name: ${{ parameters.accountName }}${NO_COLOR}"
            echo -e "${RED_BOLD}Environment: ${{ parameters.environment }}${NO_COLOR}"

  - job: WaitForValidation
    pool: server
    displayName: Wait for approval to create account
    timeoutInMinutes: 30
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 22 # task times out in 1 day
        inputs:
          notifyUsers: |
            zaki.spofy@gmail.com
            zack.fatouh@outlook.fr
          instructions: "Please validate the Decommision of the ${{ parameters.platform }} Account: ${{ parameters.accountName }}"