trigger: none

parameters:
  - name: platform
    displayName: 'Platform'
    type: string
    default: 'Aws'
    values:
      - Aws
      - Azure

  - name: clientName
    displayName: 'Client Name'
    type: string

  - name: accountName
    displayName: 'Cloud Account Name'
    type: string

  - name: environment
    displayName: 'Environment'
    type: string
    default: 'NPD'
    values:
      - NPD
      - PRD

pool:
  vmImage: ubuntu-latest

stages:
- stage: DecommissionAccount
  displayName: "Decommission Account"
  jobs:
  - job: DisplayAccountInfo
    displayName: "Display Account Decommissioning Info"
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo -e "\033[1m\033[4mDecommissioning Account Information:\033[0m"
            echo
            echo -e "\033[1mPlatform:\033[0m ${platform}"
            echo -e "\033[1mClient Name:\033[0m ${clientName}"
            echo -e "\033[1mCloud Account Name:\033[0m ${accountName}"
            echo -e "\033[1mEnvironment:\033[0m ${environment}"
            echo
            echo "================================================"
            echo -e "\033[1;31m[IMPORTANT]\033[0m Ensure you have backed up all necessary data before proceeding with decommissioning."
            echo "================================================"
            echo
            # ASCII art for critical warning
            echo -e "\033[1;31m"
            echo "     __ __   ____  _       ___   _____ ______   ___    ____  ______"
            echo "    |  |  | /    || |     /   \ / ___/|      | /   \  |    ||      |"
            echo "    |  |  ||  o  || |    |     (   \_ |      ||     |  |  | |      |"
            echo "    |  _  ||     || |___ |  O  |\__  ||_|  |_||  O  |  |  | |_|  |_|"
            echo "    |  |  ||  _  ||     ||     |/  \ |  |  |  |     |  |  |   |  |"
            echo "    |  |  ||  |  ||     ||     |\    |  |  |  |     |  |  |   |  |"
            echo "    |__|__||__|__||_____| \___/  \___|  |__|   \___/  |____|  |__|"
            echo -e "\033[0m"
            echo
            echo -e "\033[1;31m[CRITICAL WARNING]\033[0m This action is irreversible. Proceed with caution."
            echo


  - job: WaitForValidation
    pool: server
    displayName: Wait for approval to create account
    timeoutInMinutes: 30
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 22 # task times out in 1 day
        inputs:
          notifyUsers: |
            zaki.spofy@gmail.com
            zack.fatouh@outlook.fr
          instructions: "Please validate the Decommision of the ${{ parameters.platform }} Account: ${{ parameters.accountName }}"