name: Auto PR from feature branch

on:
  push:
    branches:
      - 'pizza-order-ui'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch master branch
        run: |
          git fetch origin master:master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pizza-order-ui
          base: master
          title: 'Merge pizza-order-ui into master'
          body: |
            This PR was automatically created to merge changes from the pizza-order-ui branch into master.
            Please review the changes and merge if appropriate.
